using Microsoft.Extensions.Logging;
using ZohoWhatsAppAI.Application.Common.Exceptions;
using ZohoWhatsAppAI.Application.DTOs;
using ZohoWhatsAppAI.Application.Interfaces;

namespace ZohoWhatsAppAI.Application.Services;

public class CrmSummaryService : ICrmSummaryService
{
    private readonly IZohoCrmService _zohoCrmService;
    private readonly ILeadAnalysisService _leadAnalysisService;
    private readonly IWhatsAppService _whatsAppService;
    private readonly ILogger<CrmSummaryService> _logger;

    public CrmSummaryService(
        IZohoCrmService zohoCrmService,
        ILeadAnalysisService leadAnalysisService,
        IWhatsAppService whatsAppService,
        ILogger<CrmSummaryService> logger)
    {
        _zohoCrmService = zohoCrmService;
        _leadAnalysisService = leadAnalysisService;
        _whatsAppService = whatsAppService;
        _logger = logger;
    }

    public async Task<SaveSummaryResponse> SaveSummaryAsync(
        string leadId,
        SaveSummaryRequest? request,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(leadId))
        {
            throw new ArgumentException("Lead ID cannot be empty.", nameof(leadId));
        }

        request ??= new SaveSummaryRequest();

        var lead = await _zohoCrmService.GetLeadByIdAsync(leadId, cancellationToken);
        if (lead is null)
        {
            throw new NotFoundException($"Lead '{leadId}' was not found in Zoho CRM.");
        }

        var summary = request.Summary ?? string.Empty;
        int? leadScore = request.LeadScore;
        var recommendedAction = request.RecommendedAction ?? string.Empty;
        var conversationSummary = request.ConversationSummary ?? string.Empty;

        if (request.IncludeAnalysis || string.IsNullOrWhiteSpace(summary))
        {
            var analysis = await _leadAnalysisService.AnalyzeLeadAsync(
                leadId,
                new AnalyzeLeadRequest { AdditionalContext = request.AdditionalContext },
                cancellationToken);

            summary = string.IsNullOrWhiteSpace(summary) ? analysis.LeadSummary : summary;
            leadScore ??= analysis.LeadScore;
            recommendedAction = string.IsNullOrWhiteSpace(recommendedAction)
                ? analysis.RecommendedAction
                : recommendedAction;
        }

        if (!string.IsNullOrWhiteSpace(request.ConversationTranscript))
        {
            var conversation = await _whatsAppService.GenerateConversationSummaryAsync(
                leadId,
                new ConversationSummaryRequest
                {
                    ConversationTranscript = request.ConversationTranscript,
                    AdditionalContext = request.AdditionalContext
                },
                cancellationToken);

            conversationSummary = conversation.Summary;
        }

        var noteContent = BuildNoteContent(summary, leadScore, recommendedAction, conversationSummary);
        var noteTitle = request.Title ?? $"AI Lead Summary - {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC";

        _logger.LogInformation("Saving AI summary note for lead {LeadId}.", leadId);

        var noteId = await _zohoCrmService.CreateLeadNoteAsync(
            leadId,
            noteTitle,
            noteContent,
            cancellationToken);

        return new SaveSummaryResponse
        {
            LeadId = leadId,
            NoteId = noteId,
            NoteTitle = noteTitle,
            SavedContent = noteContent,
            SavedToZoho = true
        };
    }

    private static string BuildNoteContent(
        string summary,
        int? leadScore,
        string recommendedAction,
        string conversationSummary)
    {
        var builder = new System.Text.StringBuilder();
        builder.AppendLine("=== AI Lead Qualification Summary ===");
        builder.AppendLine();
        builder.AppendLine("Lead Summary:");
        builder.AppendLine(summary);

        if (leadScore.HasValue)
        {
            builder.AppendLine();
            builder.AppendLine($"Lead Score: {leadScore.Value}/100");
        }

        if (!string.IsNullOrWhiteSpace(recommendedAction))
        {
            builder.AppendLine();
            builder.AppendLine("Recommended Action:");
            builder.AppendLine(recommendedAction);
        }

        if (!string.IsNullOrWhiteSpace(conversationSummary))
        {
            builder.AppendLine();
            builder.AppendLine("WhatsApp Conversation Summary:");
            builder.AppendLine(conversationSummary);
        }

        builder.AppendLine();
        builder.AppendLine($"Generated by ZohoWhatsAppAI on {DateTime.UtcNow:O}");

        return builder.ToString();
    }
}
